"""Add is_approved and role to User

Revision ID: e54a57867858
Revises: 4620ade3a775
Create Date: 2025-07-04 11:14:30.248696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54a57867858'
down_revision = '4620ade3a775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default=sa.text("'user'")))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
